version: "2"
linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - fatcontext
    - godot
    - godox
    - gocyclo
    - importas
    - unparam

run:
  concurrency: 4
  timeout: 5m
  tests: false
  
