version: "2"
linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - fatcontext
    - funcorder
    - godot
    - godox
    - gocritic
    - gocyclo
    - importas
    - intrange
    - mnd
    - loggercheck
    - nilnil
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - reassign
    - unconvert
    - unparam
    - varnamelen
    - wastedassign
    - zerologlint

run:
  concurrency: 4
  timeout: 5m
  tests: false
  
